### ISSUE TITLE
/bin/sh: nodejs: not found

### ISSUE THREAD

**Issue by haylinmoore** [dockette/nodejs#4]
root@hampton:~# docker run -v /root/Deploi:/srv -p 8085:8085 dockette/nodejs:v8
Unable to find image 'dockette/nodejs:v8' locally
v8: Pulling from dockette/nodejs
1eae7a7426b0: Already exists 
5acad842aeea: Already exists 
12ad30d1d788: Pull complete 
Digest: sha256:5984c15245320b6c374d410957b315558e2b454e5bf02673209aeae4a6cd50ca
Status: Downloaded newer image for dockette/nodejs:v8
/bin/sh: nodejs: not found

**Comment by f3l1x** [comment]
Fixed. Thank you.
